DROP TYPE echelon;
DROP TYPE grade;
DROP TABLE Personnel;
DROP TABLE Doctorant;
DROP TABLE Scientifique;
DROP TABLE Enseignant_Chercheur;
DROP TABLE Evenement;
DROP TABLE Congres;
DROP TABLE Labo_externe;
DROP TABLE Journee_Porte_Ouvertes;
DROP TABLE Auteur_Externe ;
DROP TABLE Publication ;
DROP TABLE Participe;
DROP TABLE Preside;
DROP TABLE Publie_Scientifique;
DROP TABLE Publie_Doctorant;
DROP TABLE Publie_Externe;
DROP TABLE Participe_Externe;
DROP TABLE Organise ;
